-- event_embeddings table + find_similar_events RPCs, extracted VERBATIM from
-- family-events-backend 20260601020000_event_embeddings_and_similarity.sql
-- (U29). Requires a pgvector-capable server image (pgvector/pgvector) for the
-- extensions.vector type. GRANT/REVOKE/RLS policies/COMMENT ON statements
-- omitted: the bare test database has no anon/authenticated/service_role
-- roles. The ai_feature_config CHECK widening, private.upsert_ai_feature_config,
-- and this file's data-update/seed statements are also not included here (the
-- catalog owns that table; test seeds own their rows).

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions;

CREATE TABLE IF NOT EXISTS public.event_embeddings (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id   uuid NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  embedding  extensions.vector(1536) NOT NULL,
  model      text NOT NULL DEFAULT 'text-embedding-3-small',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT event_embeddings_event_id_unique UNIQUE (event_id)
);

CREATE INDEX IF NOT EXISTS event_embeddings_embedding_hnsw_idx
  ON public.event_embeddings
  USING hnsw (embedding extensions.vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- No separate event_id btree index: the UNIQUE (event_id) constraint above
-- already creates one (deliberate trim vs the legacy migration).

CREATE OR REPLACE FUNCTION private.find_similar_events(
  p_embedding    extensions.vector(1536),
  p_limit        int DEFAULT 5,
  p_threshold    float DEFAULT 0.3,
  p_exclude_event_id uuid DEFAULT NULL,
  p_city_id      uuid DEFAULT NULL
)
RETURNS TABLE (
  event_id         uuid,
  title            text,
  status           public.event_status,
  cosine_distance  float,
  source_id        uuid,
  city_id          uuid
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $$
  SELECT
    e.id AS event_id,
    e.title,
    e.status,
    (ee.embedding OPERATOR(extensions.<=>) p_embedding)::float AS cosine_distance,
    e.source_id,
    e.city_id
  FROM public.event_embeddings ee
  JOIN public.events e ON e.id = ee.event_id
  WHERE (p_exclude_event_id IS NULL OR ee.event_id <> p_exclude_event_id)
    AND (p_city_id IS NULL OR e.city_id = p_city_id)
    AND (ee.embedding OPERATOR(extensions.<=>) p_embedding) < p_threshold
  ORDER BY ee.embedding OPERATOR(extensions.<=>) p_embedding
  LIMIT p_limit;
$$;

CREATE OR REPLACE FUNCTION public.find_similar_events(
  p_embedding    extensions.vector(1536),
  p_limit        int DEFAULT 5,
  p_threshold    float DEFAULT 0.3,
  p_exclude_event_id uuid DEFAULT NULL,
  p_city_id      uuid DEFAULT NULL
)
RETURNS TABLE (
  event_id         uuid,
  title            text,
  status           public.event_status,
  cosine_distance  float,
  source_id        uuid,
  city_id          uuid
)
LANGUAGE sql
SECURITY INVOKER
SET search_path TO ''
AS $$
  SELECT * FROM private.find_similar_events(
    p_embedding, p_limit, p_threshold, p_exclude_event_id, p_city_id
  );
$$;
