import { readFileSync } from "node:fs"
import { PgBoss } from "pg-boss"
import { afterAll, beforeAll, beforeEach, expect, it, vi } from "vitest"
import type { DbService } from "../../src/db/db.service.js"
import type { JobsService } from "../../src/jobs/jobs.service.js"
import { CronGateService } from "../../src/pipeline/cron-gate.service.js"
import { IngestionRepository } from "../../src/pipeline/ingestion/ingestion.repository.js"
import { TagQueueService } from "../../src/pipeline/classification/tag-queue.service.js"
import type { ClassificationRepository } from "../../src/pipeline/classification/classification.repository.js"
import type { EnrichmentRepository } from "../../src/pipeline/enrichment/enrichment.repository.js"
import { createIntegrationDb, integrationDatabaseUrl } from "./db.js"
import { ensureIngestionSchema } from "./ingestion-catalog.js"

const EVENT = "99999999-9999-4999-8999-999999999999"
const migration = "schema/migrations/20261008009000_tag_queue_ownership.sql"
const rollback = "schema/migrations/20261008009000_tag_queue_ownership_down.sql"
let db: DbService
let boss: PgBoss
let repository: IngestionRepository
let jobs: JobsService

beforeAll(async () => {
  db = createIntegrationDb()
  await ensureIngestionSchema(db)
  await db.query(`
    CREATE SCHEMA IF NOT EXISTS tag_kick_fixture;
    CREATE SCHEMA IF NOT EXISTS vault;
    CREATE SCHEMA IF NOT EXISTS net;
    CREATE TABLE vault.decrypted_secrets(name text, decrypted_secret text);
    INSERT INTO vault.decrypted_secrets VALUES
      ('supabase_project_url','http://127.0.0.1/owned-edge-fixture'),
      ('scrape_service_role_key','synthetic-tag-kick-fixture');
    CREATE TABLE tag_kick_fixture.http_calls(id bigint GENERATED ALWAYS AS IDENTITY, url text);
    CREATE FUNCTION net.http_post(url text, headers jsonb, body jsonb, timeout_milliseconds integer)
    RETURNS bigint LANGUAGE sql AS $$
      INSERT INTO tag_kick_fixture.http_calls(url) VALUES(url) RETURNING id;
    $$;
    CREATE TABLE IF NOT EXISTS private.railway_cron_runs(
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      run_key uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
      label text NOT NULL,
      status text NOT NULL,
      ran_at timestamptz NOT NULL DEFAULT now(),
      duration_s integer,
      http_status integer,
      body text
    );
  `)
  boss = new PgBoss({
    connectionString: integrationDatabaseUrl(),
    schema: "tag_kick_boss",
    schedule: false,
    supervise: false,
  })
  await boss.start()
  await boss.createQueue("tag")
  jobs = {
    send: (name: string, data: object, options: object) => boss.send(name, data, options),
  } as JobsService
  repository = new IngestionRepository(db, jobs, new CronGateService(db))
})

beforeEach(async () => {
  vi.stubEnv("NODE_ENV", "production")
  vi.stubEnv("CUTOVER_TAG", "true")
  await db.query(
    "TRUNCATE private.cron_enabled, private.railway_cron_runs, tag_kick_fixture.http_calls, tag_kick_boss.job CASCADE"
  )
  await db.query("DELETE FROM public.events WHERE id=$1", [EVENT])
  await db.query(
    "INSERT INTO public.events(id,title,start_datetime,status) VALUES($1,'Owned tag kick fixture',now(),'published')",
    [EVENT]
  )
  await db.query("INSERT INTO public.event_tag_queue(event_id) VALUES($1)", [EVENT])
  await db.query(readFileSync(migration, "utf8"))
})

afterAll(async () => {
  vi.unstubAllEnvs()
  await boss?.stop({ graceful: false })
  if (db) {
    await db.query(
      "DROP FUNCTION IF EXISTS net.http_post(text,jsonb,jsonb,integer); DROP TABLE IF EXISTS vault.decrypted_secrets; DROP SCHEMA IF EXISTS tag_kick_fixture CASCADE"
    )
    await db.onModuleDestroy()
  }
})

it("suppresses legacy Edge dispatch and reaping after tag ownership transfers to the API", async () => {
  await db.query("INSERT INTO private.cron_enabled(label,enabled) VALUES('cron-tag-queue',false)")
  await db.query(
    "UPDATE public.event_tag_queue SET status='processing',started_at=now()-interval '30 minutes' WHERE event_id=$1",
    [EVENT]
  )
  await db.query("SELECT public.invoke_process_tag_queue()")
  expect(await db.query("SELECT url FROM tag_kick_fixture.http_calls")).toEqual([])
  expect(
    await db.query("SELECT status FROM public.event_tag_queue WHERE event_id=$1", [EVENT])
  ).toEqual([{ status: "processing" }])
})

it("enqueues durable API drains with the worker's continuation key instead of Edge requests", async () => {
  await db.query("INSERT INTO private.cron_enabled(label,enabled) VALUES('cron-tag-queue',false)")
  await Promise.all([repository.invokeProcessTagQueue(), repository.invokeProcessTagQueue()])
  expect(await db.query("SELECT data,singleton_key FROM tag_kick_boss.job")).toEqual([
    { data: { task: "drain-tag-queue" }, singleton_key: "drain-tag-queue" },
    { data: { task: "drain-tag-queue" }, singleton_key: "drain-tag-queue" },
  ])
  expect(await db.query("SELECT url FROM tag_kick_fixture.http_calls")).toEqual([])
})

it("retains legacy dispatch when missing ownership gates still mean legacy owns tagging", async () => {
  await repository.invokeProcessTagQueue()
  expect(await db.query("SELECT url FROM tag_kick_fixture.http_calls")).toEqual([
    { url: "http://127.0.0.1/owned-edge-fixture/functions/v1/process-tag-queue" },
  ])
  expect(await db.query("SELECT data FROM tag_kick_boss.job")).toEqual([])
})

it.each([
  { flag: "true", operational: false },
  { flag: "false", operational: true },
])(
  "dispatches neither executor while the API is paused or uninstalled ($flag, $operational)",
  async ({ flag, operational }) => {
    vi.stubEnv("CUTOVER_TAG", flag)
    await db.query(
      "INSERT INTO private.cron_enabled(label,enabled) VALUES('cron-tag-queue',false),('nestjs:cron-tag-queue',$1)",
      [operational]
    )
    await repository.invokeProcessTagQueue()
    expect(await db.query("SELECT data FROM tag_kick_boss.job")).toEqual([])
    expect(await db.query("SELECT url FROM tag_kick_fixture.http_calls")).toEqual([])
  }
)

it("rechecks a pause before a queued tag drain can mutate the durable tag queue", async () => {
  await db.query("INSERT INTO private.cron_enabled(label,enabled) VALUES('cron-tag-queue',false)")
  await repository.invokeProcessTagQueue()
  const [job] = await boss.fetch<{ task: string }>("tag")
  expect(job?.data).toEqual({ task: "drain-tag-queue" })
  await db.query(
    "INSERT INTO private.cron_enabled(label,enabled) VALUES('nestjs:cron-tag-queue',false)"
  )
  const worker = new TagQueueService(
    jobs,
    new CronGateService(db),
    {} as ClassificationRepository,
    {} as EnrichmentRepository
  )
  await worker.handleJob(job!.data)
  expect(
    await db.query("SELECT status FROM public.event_tag_queue WHERE event_id=$1", [EVENT])
  ).toEqual([{ status: "pending" }])
  expect(await db.query("SELECT label FROM private.railway_cron_runs")).toEqual([])
})

it("restores frozen legacy dispatch on rollback and guards it again on reapply", async () => {
  await db.query("INSERT INTO private.cron_enabled(label,enabled) VALUES('cron-tag-queue',false)")
  await db.query(readFileSync(rollback, "utf8"))
  await db.query("SELECT public.invoke_process_tag_queue()")
  expect(await db.query("SELECT url FROM tag_kick_fixture.http_calls")).toHaveLength(1)
  await db.query(readFileSync(migration, "utf8"))
  await db.query("SELECT public.invoke_process_tag_queue()")
  expect(await db.query("SELECT url FROM tag_kick_fixture.http_calls")).toHaveLength(1)
})
